### ISSUE TITLE
User can create and edit study sets

### ISSUE THREAD

**Issue by michelleschofield** [michelleschofield/front-end-project-2#1]
## ⚙️ Feature

User can create a set of cards that will each have a pokemon and associated info that they would like to study

## 📐 Functionality

User can go to page to view and edit their study sets

## 🖼️ Wireframes

<img width="528" alt="Screenshot 2024-10-07 at 10 51 25 AM" src="https://github.com/user-attachments/assets/05af2191-9608-45e9-b795-7eabd0578af0">

<img width="635" alt="Screenshot 2024-10-07 at 10 52 07 AM" src="https://github.com/user-attachments/assets/a33cbbc6-215c-4774-a0b0-05de0421ce5f">

## ✅ Task List

- [x] Set up navigation system
  - [x] Create html and css for navbar
  - [x] Create menu that pops out from the side
    - [x] button at the top to hide the menu
    - [x] make each tab in loop in ts and append
      - [x] each one has the name of the view it goes to 
      - [x] each one has a data-view property with the name of the view it goes to
  - [x] Implement view swapping with temporary views for each page
  
- [x] Set up html and css for page where users view their sets
  - [x] Option to make a new set at the top
  - [x] Section for your sets
  - [x] List of sets
- [x] Set up html and css for page where users can view and edit a specific set
  - [x] Title of set at the top with edit title button
  - [x] list of cards
 
- [x] Define functions to read and write to local storage

- [ ] define a function that renders the card editing screen
- [ ] the section for the front of the card should be the same every time
- [ ] the second should check the info type of the card to determine what it should do
  - [ ] if the info type is evolves to or evolves from it should render a pokemon card
  - [ ] if the info type is flavor text it should render a text card and arrows to either side
  - [ ] if the info type is types it should render a types card (i haven't made a function that does that yet)
- [ ] there should be a change event listener on the info type select element
  - [ ] the info is retrieved from the api
  - [ ] the info type and info are updated in the card
    - [ ] a variable assigned from data will update data
  - [ ] local storage is updated
  - [ ] the display is updated

- [ ] User can make a card
  - [ ] start with default pokemon for next few steps
    - [ ] Allow user to cycle through flavor text options
      - [ ] remove all duplicate texts when query results are received
    - [ ] Allow user to select types as info option 
    - [ ] Add evolves to and from as info options
 
  - [ ] Allow user to view a list of pokemon and when they click one it is set to the pokemon for the card
  - [ ] Allow user to enter name of pokemon they would like
    - [ ] set typed name to lowercase
    - [ ] add into the url for the fetch request
    - [ ] if it doesn't return a valid pokemon show a little thing that says no pokemon can be found that matches that name
  - [ ] Allow user to search for pokemon by type
    - [ ] a list of pokemon of that type are shown
    - [ ] when one is selected alter the url provided to go to the endpoint pokemon-species instead of pokemon

- [ ] Make sure that click targets are either `<a>` or `<button>` elements.
- [ ] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- **Clean Up**
  - [ ] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [ ] Remove all console logs.
  - [ ] Remove all commented out code.
  - [ ] Remove all CSS properties that have no effect.
  - [ ] Confirm that there are no errors in the console while using the application.
  - [ ] Confirm that all previous functionality still works without errors.
  - [ ] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [ ] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
